package territorios;

public enum Tag {
    ALASKA, MACKENZIE, GROELANDIA, VANCOUVER, OTTAWA, LABRADOR, CALIFORNIA, NOVA_YORK, MEXICO, // America do Norte
    VENEZUELA, BRASIL, PERU, ARGENTINA, // America do Sul
    ISLANDIA, INGLATERRA, SUECIA, MOSCOU, FRANCA, ALEMANHA, POLONIA, // Europa
    ARGELIA, EGITO, CONGO, SUDAO, AFRICA_DO_SUL, MADAGASCAR, // Africa
    ONSK, DUDINKA, TCHITA, SIBERIA, VLADVOSTOK, ORIENTE_MEDIO, ARAL, INDIA, CHINA, VIETNAM, JAPAO, // Asia
    SUMATRA, BORNEO, NOVA_GUINE, AUSTRALIA; // Oceania
    
}
